[alias]
xclippy = [
  "clippy",
  "--workspace",
  "--all-targets",
  "--",
  "-Dwarnings",
  "-Wclippy::all",
  "-Aclippy::upper_case_acronyms",
  "-Aclippy::enum-variant-names",
  "-Aclippy::result-large-err",
  "-Aclippy::mutable-key-type",
  "-Aclippy::map_identity",  # We temporarily ignore this due to: https://github.com/rust-lang/rust-clippy/issues/11764
]
x = "run --package aptos-cargo-cli --bin aptos-cargo-cli --"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=lld", "-C", "target-feature=+sse4.2"]

# 64 bit MSVC
[target.x86_64-pc-windows-msvc]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "link-arg=/STACK:8000000" # Set stack to 8 MB
]

# macOS x86_64
[target.x86_64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

# macOS ARM64
[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]
