name: Basic check and lint

on:
  push:
    branches: [ dev-m1 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/check-and-lint.yml
  pull_request:
    branches: [ dev-m1 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/check-and-lint.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  basic-lint-and-check:
    runs-on: ubuntu-latest
    name: Basic ci-check for fmt/clippy/check
    steps:
      - uses: actions/checkout@v4

      - name: Install required deps
        run: sudo apt-get install libudev-dev libdw-dev lld

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Run check
        run: cargo check --all-targets

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
