name: Basic check and lint

on:
  push:
    branches: [ main, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/check-and-lint.yml
  pull_request:
    branches: [ main, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/check-and-lint.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  basic-lint-and-check:
    runs-on: self-hosted
    name: Basic ci-check for fmt/clippy/check
    steps:
      - uses: actions/checkout@v2

      - name: Install required deps
        run: sudo apt-get install libudev-dev libdw-dev lld

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Run check
        run: cargo check --all-targets

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test
