name: Basic test check

on:
  push:
    branches: [ main, develop-m2, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/run-tests.yml
  pull_request:
    branches: [ main, develop-m2, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/run-tests.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  basic-test-check:
    runs-on: ubuntu-latest
    name: Basic ci-check for tests
    steps:
      - uses: actions/checkout@v2

      - name: Install required deps
        run: sudo apt-get install libudev-dev libdw-dev build-essential lld

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly

      - name: Run tests
        run: cargo test
