name: Basic test run

on:
  push:
    branches: [ main, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/run-tests.yml
  pull_request:
    branches: [ main, develop-m3, develop-m4 ]
    paths:
      - Cargo.toml
      - Cargo.lock
      - move-mutator/**
      - move-spec-test/**
      - move-mutation-test/**
      - .github/workflows/run-tests.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  basic-lint-and-check:
    runs-on: self-hosted
    name: Basic ci-check for tests
    steps:
      - uses: actions/checkout@v4

      - name: Install required deps
        run: sudo apt-get install libudev-dev libdw-dev lld

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run integration tests in the release mode (due to test duration)
        run: cargo nextest run -r --profile ci test_run_mutation_test

      - name: Run normal tests in the debug mode
        run: cargo nextest run --profile ci -E 'not test(test_run_mutation_test)'

